openapi: 3.0.4
info:
  title: Telemetry API
  version: 1.0.0
servers:
  - url: http://localhost:9003
paths:
  /history:
    get:
      summary: Получить телеметрию с устройства
      parameters:
        - name: device_id
          in: query
          required: true
          schema:
            type: string
            format: uuid
        - name: date_from
          in: query
          schema:
            type: string
        - name: date_to
          in: query
          schema:
            type: string

      responses:
        '200':
          description: Данные по телеметрии
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TelemetryMessage'

        '400':
          description: Некорректные данные
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'                  
  
  /latest:
    get:
      summary: Получить последние показания телеметрии
      parameters:
        - name: device_ids
          in: query
          required: true
          schema:
            type: array
            items:
              type: string
              format: uuid
        

      responses:
        '200':
          description: Последние данные по телеметрии
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TelemetryMessage'
                  
        '400':
          description: Некорректные данные
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  
                
components:
  schemas:
    TelemetryMessage:
      type: object
      properties:
        device_id:
          type: string
          format: uuid
        timestamp:
          type: string
          format: date-time
        type:
          type: string
        data:
          type: object
          additionalProperties: true
      required:
        - device_id
        - timestamp
        - data        
        
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          example: "Invalid request"
        message:
          type: string
          example: "The provided data is invalid"
        code:
          type: integer
          example: 400
